version: "3.9"

networks:
  sdn-net:
    driver: bridge

services:
  controller:
    build: ./infra/controller
    ports:
      - "8181:8181"
    networks:
      - sdn-net

  rl-agent:
    build: ./rl_engine
    depends_on:
      - controller
    networks:
      - sdn-net
    volumes:
      - ./rl_engine:/app # Mount the rl_engine directory to /app in the container

  twin:
    build: ./digital_twin
    depends_on:
      - controller
    networks:
      - sdn-net

  mlflow:
    image: ghcr.io/mlflow/mlflow
    ports:
      - "5000:5000"
    networks:
      - sdn-net

  control_loop:
    build:
      context: .
      dockerfile: ./control_loop/Dockerfile
    container_name: control_loop
    depends_on:
      - controller
      - rl-agent
    networks: 
      - sdn-net
        
