version: "3.8"

networks:
  sdn-net:
    driver: bridge

services:
  controller:
    image: onosproject/onos:2.7.0
    container_name: onos-controller
    ports:
      - "8181:8181" # Web GUI & REST API
      - "6653:6653" # Port giao tiếp OpenFlow với Mininet
      - "8101:8101" # Karaf SSH
    networks:
      - sdn-net
    environment:
      # Tự động kích hoạt các App cần thiết của ONOS khi khởi động
      - ONOS_APPS=drivers,openflow,gui,fwd,proxyarp,hostprovider,linkprovider,flowruleprovider,statisticspublisher,prometheus
      - ONOS_AUTO_START=true
    restart: always

  # Container chạy DQN
  rl-agent-dqn:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rl-agent-dqn
    depends_on:
      - mlflow
      - controller
    ports:
      - "9000:9000"
    networks:
      - sdn-net
    volumes:
      - .:/app
      - ./results:/app/results
      - ./models:/app/models
      - ./logs:/app/logs
      - ./mlruns:/app/mlruns
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - CI=false
    command: python -m rl_engine.agent.train_dqn
    restart: on-failure

  # Container chạy PPO
  rl-agent-ppo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rl-agent-ppo
    depends_on:
      - mlflow
      - controller
    ports:
      - "9001:9001"
    networks:
      - sdn-net
    volumes:
      - .:/app
      - ./results:/app/results
      - ./models:/app/models
      - ./logs:/app/logs
      - ./mlruns:/app/mlruns
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - CI=false
    command: python -m rl_engine.agent.train_ppo
    restart: on-failure

  # twin:
  #   build: ./digital_twin
  #   depends_on:
  #     - controller
  #   networks:
  #     - sdn-net

  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.0.0
    container_name: mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
    environment:
      - BACKEND_STORE_URI=sqlite:////mlflow/mlflow.db
      - DEFAULT_ARTIFACT_ROOT=/mlflow/artifacts
    #command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:////mlflow/mlflow.db --default-artifact-root /mlflow/artifacts --allowed-hosts "*"
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:////mlruns/mlflow.db
      --default-artifact-root /mlruns/artifacts
    networks:
      - sdn-net
    #healthcheck:
    #  test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000')"]
    #  interval: 10s
    #  timeout: 5s
    #  retries: 5

  # Control Loop
  control_loop:
    build:
      context: .
      dockerfile: ./control_loop/Dockerfile
    container_name: control_loop
    depends_on:
      - controller
      - rl-agent-dqn
      - rl-agent-ppo
      - mlflow
    networks:
      - sdn-net
    environment:
      - PYTHONUNBUFFERED=1
      - MLFLOW_TRACKING_URI=http://mlflow:5000
        
  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - sdn-net
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: unless-stopped
    
  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - sdn-net
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/sdn_rl_dashboard.json
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus
    restart: unless-stopped

  # AlertManager
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    networks:
      - sdn-net
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    restart: unless-stopped
  
  # Auto Trigger (MLOps)
  auto-trigger:
    build:
      context: ./mlops
      dockerfile: Dockerfile
    container_name: auto-trigger
    ports:
      - "5001:5001"
    networks:
      - sdn-net
    environment:
      - SERVICE_MODE=trigger
      - PYTHONUNBUFFERED=1
    command: python main.py
    depends_on:
      - alertmanager
    restart: on-failure

volumes:
  mlflow_data:
  prometheus_data:
  grafana_data:
