global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "sdn-rl-monitor"

# Load rules once and periodically evaluate them
rule_files:
  - "alert.rules.yml"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # ONOS Controller
  # - job_name: "onos"
  #   static_configs:
  #     - targets: ["controller:8181"]
  #   metrics_path: "/onos/v1/network/configuration"
  #   basic_auth:
  #     username: "onos"
  #     password: "rocks"

  # Cấu hình "cào" dữ liệu từ quá trình huấn luyện DQN (Container rl-agent-dqn)
  - job_name: "rl-agent-dqn"
    static_configs:
      # Sửa tên host thành 'rl-agent-dqn' và cổng '9002'
      - targets: ["rl-agent-dqn:9002"]

  # Cấu hình "cào" dữ liệu từ quá trình huấn luyện PPO (Container rl-agent-ppo)
  - job_name: "rl-agent-ppo"
    static_configs:
      # Sửa tên host thành 'rl-agent-ppo' và cổng '9003'
      - targets: ["rl-agent-ppo:9003"]

  # Cấu hình "cào" dữ liệu từ quá trình dự đoán (Inference) của DQN
  - job_name: "rl-serving-dqn"
    static_configs:
      # Sửa tên host thành 'rl-serving-dqn' và cổng '9002'
      - targets: ["rl-serving-dqn:9002"]

  # Cấu hình "cào" dữ liệu từ quá trình dự đoán (Inference) của PPO
  - job_name: "rl-serving-ppo"
    static_configs:
      # Sửa tên host thành 'rl-serving-ppo' và cổng '9003'
      - targets: ["rl-serving-ppo:9003"]
  # Control Loop (Runtime metrics)
  - job_name: "control_loop"
    static_configs:
      - targets: ["control_loop:9100"]
    scrape_interval: 10s

  - job_name: "sdn-defense-agent"
    scrape_interval: 2s
    static_configs:
      - targets: ["sdn-defense-agent:8000"]

  # - job_name: "minio_storage"
  #   metrics_path: /minio/v2/metrics/cluster
  #   static_configs:
  #     - targets: ["s3:9005"]
  #   params:
  #     auth: ["public"]
