apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: sdn-security
spec:
  replicas: 1
  selector: { matchLabels: { app: alertmanager } }
  template:
    metadata: { labels: { app: alertmanager } }
    spec:
      containers:
        - name: alertmanager
          image: prom/alertmanager:latest
          args:
            - "--config.file=/etc/alertmanager/alertmanager.yml"
          ports: [{ containerPort: 9093 }]
          volumeMounts:
            - name: config
              mountPath: /etc/alertmanager
      volumes:
        - name: config
          configMap: { name: alertmanager-config }
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: sdn-security
spec:
  type: NodePort
  selector: { app: alertmanager }
  ports:
    - port: 9093
      targetPort: 9093
      nodePort: 30093 # Truy cập qua http://<IP>:30093
