apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-loop
  namespace: sdn-security
spec:
  replicas: 1
  selector: { matchLabels: { app: control-loop } }
  template:
    metadata:
      labels: { app: control-loop }
    spec:
      containers:
        - name: loop
          image: hmm0411/sdn-control-loop:latest
          command: ["python", "control_loop/main_loop.py"]
          env:
            - name: PYTHONPATH
              value: "/app"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-trigger
  namespace: sdn-security
spec:
  replicas: 1
  selector: { matchLabels: { app: auto-trigger } }
  template:
    metadata:
      labels: { app: auto-trigger }
    spec:
      serviceAccountName: auto-trigger-sa
      containers:
        - name: trigger
          image: hmm0411/sdn-auto-trigger:latest
          command: ["python", "main.py"]
          env:
            - name: PYTHONPATH
              value: "/app"
