apiVersion: apps/v1
kind: Deployment
metadata:
  name: rl-serving-dqn
  namespace: sdn-security
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rl-serving-dqn
  template:
    metadata:
      labels:
        app: rl-serving-dqn
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: serving
          image: hmm0411/sdn-rl-serving:latest
          command: ["python", "serving.py", "--port", "8000"]
          env:
            - name: PYTHONPATH
              value: "/app"
            - name: MODEL_TYPE
              value: "dqn"
            - name: MLFLOW_TRACKING_URI
              value: "http://mlflow:5000"
          securityContext:
          runAsUser: 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rl-serving-ppo
  namespace: sdn-security
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rl-serving-ppo
  template:
    metadata:
      labels:
        app: rl-serving-ppo
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: serving
          image: hmm0411/sdn-rl-serving:latest
          command: ["python", "serving.py", "--port", "8001"]
          env:
            - name: PYTHONPATH
              value: "/app"
            - name: MODEL_TYPE
              value: "ppo"
            - name: MLFLOW_TRACKING_URI
              value: "http://mlflow:5000"
          securityContext:
            runAsUser: 0
