apiVersion: v1
kind: Namespace
metadata:
  name: sdn-security
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auto-trigger-sa
  namespace: sdn-security
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-creator-role
  namespace: sdn-security
rules:
  - apiGroups: ["batch", "apps"]
    resources: ["jobs", "deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-creator-binding
  namespace: sdn-security
subjects:
  - kind: ServiceAccount
    name: auto-trigger-sa
roleRef:
  kind: Role
  name: job-creator-role
  apiGroup: rbac.authorization.k8s.io
