apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: sdn-security
type: Opaque
stringData:
  ACCESS_KEY: "minioadmin"
  SECRET_KEY: "minioadmin"
---
# ==========================================
# MINIO (STORAGE)
# ==========================================
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: s3
  namespace: sdn-security
spec:
  serviceName: "s3"
  replicas: 1
  selector:
    matchLabels:
      app: s3
  template:
    metadata:
      labels:
        app: s3
    spec:
      containers:
        - name: minio
          image: minio/minio:latest
          volumes:
            - name: data
              mountPath: /data
          command:
            [
              "server",
              "/data",
              "--address",
              ":9005",
              "--console-address",
              ":9001",
            ]
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: ACCESS_KEY
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: SECRET_KEY
            - name: MINIO_PROMETHEUS_AUTH_TYPE
              value: "public"
          ports:
            - containerPort: 9005
            - containerPort: 9001

---
apiVersion: v1
kind: Service
metadata:
  name: s3
  namespace: sdn-security
spec:
  selector:
    app: s3
  ports:
    - name: api
      port: 9005
      targetPort: 9005
    - name: console
      port: 9001
      targetPort: 9001
---
# ==========================================
# MLFLOW (TRACKING)
# ==========================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: sdn-security
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: ghcr.io/mlflow/mlflow:v3.0.0
          command:
            [
              "mlflow",
              "server",
              "--host",
              "0.0.0.0",
              "--port",
              "5000",
              "--default-artifact-root",
              "s3://mlflow-artifacts",
            ]
          env:
            - name: MLFLOW_S3_ENDPOINT_URL
              value: "http://s3:9005"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: ACCESS_KEY
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: SECRET_KEY
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: sdn-security
spec:
  selector:
    app: mlflow
  ports:
    - port: 5000
      targetPort: 5000
