# prometheus lấy dữ liệu từ DQN và PPO
global:
  scrape_interval: 5s

rule_files:
  - "alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  # DQN
  - job_name: 'rl-agent-dqn'
    static_configs:
      - targets: ['rl-agent-dqn:9000']

  # PPO
  - job_name: 'rl-agent-ppo'
    static_configs:
      - targets: ['rl-agent-ppo:9001']
