name: NT549 CI

on:
  push:
    branches:
      - nt549-rl

jobs:
  test-rl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r rl_engine/requirements.txt

      - name: Create Data Directory
        run: |
          mkdir -p data/processed
      
      - name: Download Dataset
        run: |
          wget -q -O data/processed/train_data.csv "https://github.com/user-attachments/files/26481488/train_data.csv"
          wget -q -O data/processed/test_data.csv "https://github.com/user-attachments/files/26481487/test_data.csv"

          ls -la data/processed/

      - name: Run Environment Test
        env:
          PYTHONPATH: .
        run: |
          python -c "
          import pandas as pd
          from rl_engine.env import SDNEnv
          from rl_engine.offline_env import OfflineSDNEnv
          print('1. Testing Offline Env...')
          df_train = pd.read_csv('data/processed/train_data.csv')
          offline_env = OfflineSDNEnv(dataframe=df_train)
          offline_env.reset()
          
          print('2. Testing Online Env (Mock Controller)...')
          online_env = SDNEnv()
          online_env.reset()
          
          print('Cả 2 Environment đều khởi tạo thành công!')
          "

      - name: Run RL Training Test
        env:
          PYTHONPATH: .
          CI: "true"
        run: |
          cd experiments
          python evaluate.py
